# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [-c.markdownlint.yaml]
      - id: markdownlint-fix
        args: [-c.markdownlint.yaml]

  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.27
    hooks:
      - id: conform
        stages:
          - commit-msg

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: [
          -L,
          'ser,exite,lew,isplay,erro,hart,hve,som,gir,\
          synopsys,uests,datas,synopsys,tung,ot,hda,parm,hsi'
        ]

  - repo: local
    hooks:
      - id: double_slashes_url_external
        name: Check double slashes in external URLs
        entry: https?:\/\/[^\s]*(?<!http:)((?<!https:)\/\/).*
        language: pygrep
        exclude: '^.*.(jpeg|jpg|png|pdf)$'
      - id: double_slashes_url_markdown
        name: Check double slashes in markdown URLs
        entry: (^[^\s]*\:\s|]\()[^\s)]*(?<!git:)((?<!http:)((?<!https:)\/\/))
        language: pygrep
        exclude: '^.*.(jpeg|jpg|png|pdf)$'
      - id: hugo_rss_outputs_home
        name: Ensure Hugo home outputs include RSS
        entry: bash -c 'grep -qE "^\s*home\s*=\s*\[.*\"RSS\".*\]" blog/config.toml'
        language: system
        files: ^blog/config.toml$
      - id: hugo_rss_outputs_section
        name: Ensure Hugo section outputs include RSS
        entry: bash -c 'grep -qE "^\s*section\s*=\s*\[.*\"RSS\".*\]" blog/config.toml'
        language: system
        files: ^blog/config.toml$
      - id: rss_autodiscovery_guarded
        name: Ensure RSS link tags are within with-block
        entry: bash -c 'grep -qE "{{\s*with\s*\.OutputFormats\.Get\s*\"RSS\"\s*}}" blog/themes/3mdeb/layouts/partials/header.html'
        language: system
        files: ^blog/themes/3mdeb/layouts/partials/header\.html$

ci:
  autoupdate_commit_msg: 'pre-commit: autoupdate hooks'
  autofix_prs: false
