dist: xenial

env:
  global:
  - HUGO_VERSION="0.54.0"
  - HUGO_TAR="hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
  - HUGO_URL="https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_TAR}"
  - secure: "q2wxEjTYnAgc5dxxonLbvXaZ6PMaXwnwEeC8WpFZmHRPCtWLVbth3Aozc/HdhXNZoUzvszPuZ79JepO7n0b4i2DVRtywVOEhm/6XomcTsfkQejyS3N3O/x1+BxG2gOhsRQQg7MSw0Zl/uZuh7DWCYZcw2yL8t6VcAdkqraIWa/0vneOJaPuU6w5Z1Ql0ZHdV3M9qptDCiw23X7DI6jTnRxIUzhCTueh/ErYyow4LOzhjxgq8EiRY9N98q/zCGxw2JUiyPqMJay+pFITown69B68wKGHhfcfbTrgFPzC6jHkQVipGTjkZX6DJx4tX5cTBCqB98wsU5EMW+mjNUn5v7xNq2fZJbqmIH/JrsixSB7xCjNlb2wkQFmPJbqm/oJu0/ZL/HIpybjpONc9Afix1dskocJ79y9vEnPBnem70H0MDunpyJWmwRowaDV8Hy79C2easEe9unu3QajhXgVnTmoGjnU78seZLYwmhfe1lj5wEZRNxe/eq59frKszdfTizaeqJ+SwCzUJ7c3wqtyUGes+D4JYEGAYvN+lKTPg7t2ZI7rfFN6jEqd3nAG9h8A1nxLfAapEHNOSesLTSMWt41t6fDjtxxg0/zbdRO/oYV4tl9AMyXI5by1+5o78fGqNaQ7nSk+m2UVJZELGIFZ+zS5vkghf/6HQnfBEylm0jC9k="
  - secure: "n8EZdqdepY/6ANb7EmbimEb107h0yZ6GZLZZcmTWdW2Vh9A2hh1UYp14tTCXctG1mWU+tQi/pLklVjK3T4f56o8carb9gQ6s1E7LUS3SHJ7VqwazOZomIwtJ4G/IBGCfN0/8hkHKTwJuXZZxJQ2vzZ8+VG1N4lXVthVh79Ha+Bz3/BYsP/ER2uv99II4L2rRtjafiIwj3VWKgvQLthzF6lAztoy3H2Y0dyj7f6wspjVfA+Va5wQvPB5+rhLrAFLP2v8X7yh6V31uTygYMd9xgqzhmg3/P2faGEJjve7HWa2lurMuYCpwOQg3UG/pAHrLVe7l1UmYP3aSxiHGolo4NcPxL8vIp2/pOqfIYmvYU8VVksIVSh09AzK+Q58WkCjHakxbFeyAxTrS780ofSsp7qxU97qb9iFvD9rgk0+sT/l3/W/5eDy5GWfXvL14K1Q0exRen3pFVmB4oDNyG5VSxNhgmVckzjHCVgU74MNMVi7BzS156pDhWel8UrZbMbtM+bShXR57/6RTsG9ajuQJG4EebooraNswUR+PZwbFhIesK/1fH1WuQqLJVizSMQWQs6g3c/XORkBkoPeA2qc1P0u9R1fz6mkoz2KTy8yK3hTid07eQUqQS2xhnGS9CkhEyPmhG9xpGW0fB6g8JwCYPmVHfOtIU1JDxOsZxWyNuaU="
  - secure: "LIM8kCk/PqSJ0rVo360VOwes3GFODclwCFT9r5td1SA6VLqPVWTYfhE1OxXXa9x3MpoyIrLvax+wPFaMut+jnzo1Qpnz79bHl8/5MqGXijY8GofTVz2DvKS0+WDXQYzX8KxByj+3FrmeAcSiFpKfSfv+WIO2mD8KsZwJuas8x2LBdM7jtll0VEmXlouTn6ovwqd02vuUuYLykpKSr9p5XTKrxygUErsId/2eLz0YKBFszE0cz6rUZgb9akGRUK0Hd2mI6n5/6JLbxv/4T5/L1jupiAZwADGVj4B477/XCgnlk6rDPs6LudWaXzv9NesKd4qPrONi1vzzx8N0X0hhrpwGvhd6zLPtfM5BA76C97W7jRKDnJsaTeJa4pJebiHMCUKUM3RWdIQwwURWkw5FKHoKaNN9h+SAH0aPGfAzs5nd8RLd3y5DB2DFR0LYCC3X+HDSF3XLI3om+TusvtEdDo1LdkTm/be359NseKQNtGkuU0BnbEJxp7jwsBwa526sUBnXG+PbNts50ppLRJ/yfODKb+vOrLSem5fh96YH8OwdYEPOmc8vkH15ZX4iq3l+Su26yxRsrdQqmEZJo90HRnI+454eq0oGq8Zxa/rjvJ0GBmr+lawSKSvBvC0wGDsyuEva6Rrj+N8AsibLkySq4LozpQ5FQ/dw50ckXQip1yk="
  - secure: "hMPXiP64y+1FjJ1AkSa/jC1WPTUyEiIgCRZVL2+xAF/8EyLnsWxrtAZR5OC8VoZkcnd65WGjV07EiKmwnWh/fRtDAlzWuZFzHGnWEixDUQC90sg5HwLdYWwKIKVsvhAiP1XLpyQfSpN8EFMQSFjTJCG8ZPgk7ewYLY4rWWOBkp8RHG7OOuimxiRTCKVdIRhdkVf6N+FpARa3y5noY/KYlmEpBelaIm6hDf8pu5R1O7FD/EI9IhiKDPMJl5i2jfR1+GnBcpnI5fT7OImaO5W7ssqT+PQ/bdPMStTQymAn5TU2nTWdcwGcUY/SfeSHc4uwUz0aODjS8tr2BDvTFJlHKR8kXSLwjEbeU7L9VB5xxxaCLoKVDNqQPCmORQ0KO00mmKQzKmMgsWc+Hop/BJMsmFZ6Xwh/9u4qSoNjmwU+AvE+vl1VkMOD7zs8MFbRHMQdozO2jc+32RkUYmGA3IGf9LmjuxEFVvV0sTSHzh9kdl1lcPhziWMVAEaGTy1ze2gDtsdKVNfZv42zi70eY+192CI5UkpBETascmuEOMaYnsekqNcE0Xpvw76a8esEPTBCHO55Djhu1YJGscAY8tVnKddTMIC9VuSAazhdykbgMHIjA+1z/JTZOnsAaYXyQXxJIojiAthjLgYUaxL6fJ3xJ4OcUttcS0cjO/I+Ze6jEfY="
  - secure: "U8d3yHbVzwkXY28yvF/6GnvZBtq2/6zEx/XGEWb32pIzoHPyIpdiuvP3hM2nXi/Sy0qiyFoZQ54JJod3mkx4IHJIaq7Qw0YRsVVBT491dCkUuGuoneOvTW1wIyUW2S8Wu/0lB14U381S+rCEqfCwtrwfD0nsx5ufK4w7cjX9q0qCpgpxUqkMXsdrnu8R0qZk5eaLccunxRdrJwWjxZlQqTTMSjZ6qEML3NIX4Xs7hHqrXdSlvoNKh/kbdelV42eVRxQooYgSj5QSTFk5QzkPJfGDd4dXglU+EPWbfla/iT56B0tUE/oVFKwLdl6R42NuDoYQzG1TVCkAVl//tkth7GLF5RFt4au9h66l5/RP17RiZ19ZiLeIYwP1BoMvenIF/8BCo6VojfFkWDeXLKfPSgSSH4V2SQ5VRIMMRb4TpIEW76R6Cw5f0fgCNbsMKMGd+Kn9k6ykEf5Jsd1sxlkm7dHStHba39uU9Io+z4m7TaLxD5D9gqus4fYO2Ya90PF5Rmb2m5hGWQhG2Xux936zj9BYGknmWwQGV4iP4rMz+ttOfJgzkSwRr/kR/OU3ewXdMEAVAVvVC0lS8frTtw+tfW+2ohmoEu67ZKYGhHW6iq4I2YWLpqU1vy97htuPDqwl2WKXDSQ2/AuiqXtS8mC/sn7iqwQZ0ToGEnf2d7kb0pA="

git:
  depth: 1

notifications:
  email: false

before_install:
  - cd ${TRAVIS_BUILD_DIR}/blog
  - wget ${HUGO_URL}
  - tar xf ${HUGO_TAR}

script:
  - cd ${TRAVIS_BUILD_DIR}/scripts && bash build.sh

before_deploy:
  - sudo apt-get update
  - sudo apt-get install -y sshpass

deploy:
  provider: script
  script: cd ${TRAVIS_BUILD_DIR}/scripts && bash deploy.sh
  skip_cleanup: true
  on:
    branch:
      - travis
      - develop
      - master
