post_title: Robot Framework - using Request library for control RPI GPIO's
author: Daniel Konopski
layout: post
published: false
post_date: 2017-10-12 14:31:00
tags: 
  - Robot Framework 
  - Request Library
  - REST API
categories:
  - Validation
