baseURL = "https://beta.blog.3mdeb.com/"
languageCode = "en-us"
title = "Thoughts dereferenced from the scratchpad noise."

theme = "3mdeb"

[outputFormats]
  [outputFormats.RSSAlt]
    mediaType = "application/rss+xml"
    baseName = "rss"
  [outputFormats.Feed]
    mediaType = "application/rss+xml"
    baseName = "feed"

pygmentsCodefences = true
pygmentsStyle = "solarized-dark"
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

enableRobotsTXT = true
googleAnalytics = "G-6TLWTXF995"

[permalinks]
    post = "/:year/:filename"
    archive = "/archives/:year/"

[taxonomies]
    archive = "archives"
    category = "categories"
    author = "authors"
    tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = ["HTML","RSS","RSSAlt","Feed"]
  section = ["HTML","RSS"]

rssLimit = 50

