baseURL = "https://beta.blog.3mdeb.com/"
languageCode = "en-us"
title = "Thoughts dereferenced from the scratchpad noise."

theme = "3mdeb"

pygmentsCodefences = true
pygmentsStyle = "solarized-dark"
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

googleAnalytics = "G-6TLWTXF995"
disqusShortname = "pietrushnics-world"

[permalinks]
    post = "/:year/:filename"
    archive = "/archives/:year/"

[taxonomies]
    archive = "archives"
    category = "categories"
    author = "authors"
    tag = "tags"

[markup.goldmark.renderer]
unsafe = true
